# Form implementation generated from reading ui file 'launcher.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Launcher(object):
    def setupUi(self, Launcher):
        Launcher.setObjectName("Launcher")
        Launcher.resize(640, 320)
        Launcher.setMinimumSize(QtCore.QSize(640, 320))
        Launcher.setMaximumSize(QtCore.QSize(640, 320))
        Launcher.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Launcher.setWindowIcon(icon)
        Launcher.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Ukrainian, QtCore.QLocale.Country.Ukraine))
        self.centralwidget = QtWidgets.QWidget(Launcher)
        self.centralwidget.setObjectName("centralwidget")
        self.newgame_btn = QtWidgets.QPushButton(self.centralwidget)
        self.newgame_btn.setGeometry(QtCore.QRect(10, 130, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.newgame_btn.setFont(font)
        self.newgame_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.newgame_btn.setStyleSheet("background-color: #7f5af0;\n""color: #fffffe\n""")
        self.newgame_btn.setObjectName("newgame_btn")
        self.continue_btn = QtWidgets.QPushButton(self.centralwidget)
        self.continue_btn.setGeometry(QtCore.QRect(10, 180, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.continue_btn.setFont(font)
        self.continue_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.continue_btn.setStyleSheet("background-color: #7f5af0;\n""color: #fffffe\n""")
        self.continue_btn.setObjectName("continue_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 641, 321))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/launcher.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.newgame_btn.raise_()
        self.continue_btn.raise_()
        Launcher.setCentralWidget(self.centralwidget)

        self.retranslateUi(Launcher)
        QtCore.QMetaObject.connectSlotsByName(Launcher)

    def retranslateUi(self, Launcher):
        _translate = QtCore.QCoreApplication.translate
        Launcher.setWindowTitle(_translate("Launcher", "Launcher"))
        self.newgame_btn.setText(_translate("Launcher", "Новая игра"))
        self.continue_btn.setText(_translate("Launcher", "Продолжить "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Launcher = QtWidgets.QMainWindow()
    ui = Ui_Launcher()
    ui.setupUi(Launcher)
    Launcher.show()
    sys.exit(app.exec())
